# Generated by Django 3.1.1 on 2020-12-19 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_auto_20201219_2033'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('countrys', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='country',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.country'),
        ),
    ]
